// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Data.DbContexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20251207232409_BorrowModuels")]
    partial class BorrowModuels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain_Layer.Models.Authors_Models.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1000L);

                    b.Property<string>("Auth_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Domain_Layer.Models.Book_Authors_Models.Book_Authors", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book_Authors");
                });

            modelBuilder.Entity("Domain_Layer.Models.Book_Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("ShelfId")
                        .HasColumnType("int");

                    b.Property<string>("TiTle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<int>("puplisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShelfId");

                    b.HasIndex("puplisherId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Domain_Layer.Models.Borrow_Models.Borrow", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBorrow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("BookId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<int?>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "UserId", "DateBorrow");

                    b.HasIndex("BookId1")
                        .IsUnique()
                        .HasFilter("[BookId1] IS NOT NULL");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId1");

                    b.HasIndex("UserId");

                    b.HasIndex("UsersId");

                    b.ToTable("Borrows", t =>
                        {
                            t.HasCheckConstraint("CheckDate", "DateBorrow > DueDate");

                            t.HasCheckConstraint("ValidAmount", "Amount <= 3");
                        });
                });

            modelBuilder.Entity("Domain_Layer.Models.Categories_Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Domain_Layer.Models.Employee_Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bouns")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("FloorsNumber")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FloorsNumber");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("GymUserValidEmailCheck", "Email Like '_%@_%._%'");

                            t.HasCheckConstraint("GymUserValidPhoneNumberCheck", "PhoneNumber Like '01%' and PhoneNumber Not Like '%[^0-9]%'");

                            t.HasCheckConstraint("ValidSalary", "Salary >= 4000");
                        });
                });

            modelBuilder.Entity("Domain_Layer.Models.Floors_Models.Floors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FloorNumber");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 100L, 100);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("HiringDate")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("EmployeeMangeId")
                        .HasColumnType("int");

                    b.Property<int>("Number_of_Blocks")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeMangeId")
                        .IsUnique()
                        .HasFilter("[EmployeeMangeId] IS NOT NULL");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Domain_Layer.Models.Puplishers_Models.Puplishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 5L, 10);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Publisher_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("Puplishers");
                });

            modelBuilder.Entity("Domain_Layer.Models.Shelf_Models.Shelf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("FloorNumber");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("Domain_Layer.Models.Users_Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L, 10);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("User_Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("User_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("User_Phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("GymUserValidEmailCheck", "User_Email Like '_%@_%._%'")
                                .HasName("GymUserValidEmailCheck1");

                            t.HasCheckConstraint("GymUserValidPhoneNumberCheck", "User_Phone Like '01%' and User_Phone Not Like '%[^0-9]%'")
                                .HasName("GymUserValidPhoneNumberCheck1");
                        });
                });

            modelBuilder.Entity("Domain_Layer.Models.Book_Authors_Models.Book_Authors", b =>
                {
                    b.HasOne("Domain_Layer.Models.Authors_Models.Authors", "Author")
                        .WithMany("Book_Authors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain_Layer.Models.Book_Models.Book", "Book")
                        .WithMany("Book_Authors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain_Layer.Models.Book_Models.Book", b =>
                {
                    b.HasOne("Domain_Layer.Models.Categories_Models.Categories", "Category")
                        .WithMany("Book")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain_Layer.Models.Shelf_Models.Shelf", "Shelf")
                        .WithMany("Book")
                        .HasForeignKey("ShelfId");

                    b.HasOne("Domain_Layer.Models.Puplishers_Models.Puplishers", "puplisher")
                        .WithMany("Book")
                        .HasForeignKey("puplisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Shelf");

                    b.Navigation("puplisher");
                });

            modelBuilder.Entity("Domain_Layer.Models.Borrow_Models.Borrow", b =>
                {
                    b.HasOne("Domain_Layer.Models.Book_Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain_Layer.Models.Book_Models.Book", null)
                        .WithOne("Borrow")
                        .HasForeignKey("Domain_Layer.Models.Borrow_Models.Borrow", "BookId1");

                    b.HasOne("Domain_Layer.Models.Employee_Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain_Layer.Models.Employee_Models.Employee", null)
                        .WithMany("Borrows")
                        .HasForeignKey("EmployeeId1");

                    b.HasOne("Domain_Layer.Models.Users_Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain_Layer.Models.Users_Models.Users", null)
                        .WithMany("Borrows")
                        .HasForeignKey("UsersId");

                    b.Navigation("Book");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain_Layer.Models.Employee_Models.Employee", b =>
                {
                    b.HasOne("Domain_Layer.Models.Floors_Models.Floors", "Floors")
                        .WithMany("employeesWork")
                        .HasForeignKey("FloorsNumber")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain_Layer.Models.Employee_Models.Employee", "Supervisor")
                        .WithMany("Subordinates")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Domain_Layer.Models.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("Area");

                            b1.Property<int>("BuildingNumber")
                                .HasColumnType("int")
                                .HasColumnName("BuildingNumber");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("Country");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("varchar")
                                .HasColumnName("Street");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Floors");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Domain_Layer.Models.Floors_Models.Floors", b =>
                {
                    b.HasOne("Domain_Layer.Models.Employee_Models.Employee", "EmployeeMange")
                        .WithOne("FloorsMange")
                        .HasForeignKey("Domain_Layer.Models.Floors_Models.Floors", "EmployeeMangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EmployeeMange");
                });

            modelBuilder.Entity("Domain_Layer.Models.Shelf_Models.Shelf", b =>
                {
                    b.HasOne("Domain_Layer.Models.Floors_Models.Floors", "Floor")
                        .WithMany("Shelfs")
                        .HasForeignKey("FloorNumber");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Domain_Layer.Models.Users_Models.Users", b =>
                {
                    b.HasOne("Domain_Layer.Models.Employee_Models.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain_Layer.Models.Authors_Models.Authors", b =>
                {
                    b.Navigation("Book_Authors");
                });

            modelBuilder.Entity("Domain_Layer.Models.Book_Models.Book", b =>
                {
                    b.Navigation("Book_Authors");

                    b.Navigation("Borrow");
                });

            modelBuilder.Entity("Domain_Layer.Models.Categories_Models.Categories", b =>
                {
                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain_Layer.Models.Employee_Models.Employee", b =>
                {
                    b.Navigation("Borrows");

                    b.Navigation("FloorsMange");

                    b.Navigation("Subordinates");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain_Layer.Models.Floors_Models.Floors", b =>
                {
                    b.Navigation("Shelfs");

                    b.Navigation("employeesWork");
                });

            modelBuilder.Entity("Domain_Layer.Models.Puplishers_Models.Puplishers", b =>
                {
                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain_Layer.Models.Shelf_Models.Shelf", b =>
                {
                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain_Layer.Models.Users_Models.Users", b =>
                {
                    b.Navigation("Borrows");
                });
#pragma warning restore 612, 618
        }
    }
}
